# name: Protect YAML File

# on:
#   pull_request:
#     paths: '.github/workflows/github-actions-branch.yml'

# jobs:
#   check-yaml:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Check if YAML file was modified
#         run: |
#           if git diff --name-only HEAD^ HEAD | grep -q '.github/workflows/github-actions-branch.yml'; then
#             echo "YAML file was modified. Rejecting the PR."
#             exit 1
#           else
#             echo "YAML file was not modified."
#           fi

name: Protect YAML Files

on: pull_request

jobs:
    check-yaml:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Prevent file change
          uses: xalvarez/prevent-file-change-action@v1
          with:
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            pattern: .*\.yml
            trustedAuthors: xalvarez
            allowNewFiles: false
