name: Check file changes

on:
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check if file has changed
      run: |
        if git diff --quiet main..HEAD -- .github\workflows\github-actions-branch.yml; then
          echo "File github-actions-branch.yml has not changed"
          exit 0
        else
          echo "File github-actions-branch.yml has changed"
          exit 1
        fi
