name: Branchlint

on:
  pull_request:
    branches:
      - "main"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint branch name
        uses: lekterable/branchlint-action@2.1.0
        with:
          allowed: |
            develop
            /(feature|fix|hotfix)/lab-\d+/.+/
          errorMessage: "Invalid branch name"
      - name: Compare workflow file with reference
        run: |
          diff -q .github/workflows/github-actions-branch.yml reference/.github/workflows/github-actions-branch.yml
